title: Filipe Silva
description: 

url: https://filipeosilva.github.io/oldBlog/
paginate_path: "/oldBlog/blog/page:num/"
permalink: oldBlog/blog/:oldBlog/title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /oldBlog/index.html
  - title: About
    url: /oldBlog/about

social:
  github: 
  twitter:
  facebook:
  email: 
  linkedin: 

disqus:
    shortname: 
