title: Filipe Silva
description: 

baseurl: /oldBlog
url: "https://filipeosilva.github.io"

paginate_path: oldBlog/blog/page:num/
permalink: oldBlog/blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10

navigation:
  - title: Home
    url: oldBlog/index.html
  - title: About
    url: oldBlog/about

social:
  github: 
  twitter:
  facebook:
  email: 
  linkedin: 

disqus:
    shortname: 
